version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db
   volumes:
     - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  lichessengine:
    image: 'lichessengine:latest'
    build:
      context: .
    container_name: lichessengine
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
